server:
  port: 8001
  servlet:
    context-path: /app

spring:
  application:
    name: app

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.19.103.2:3306/cloud_desk?serverTimeZone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: cloud_desk_dbu
    password: admin312


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.wtao.mybatis.generator.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
